'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace webserver
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ClientServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClientService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private HelloWorldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DevolveIncidenteIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetIncidenteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DevolveTipoIncidentesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DevolveIncidentesActivosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DevolveMeusIncidentesActivosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DevolveActividadesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DevolveActividadesEdicaoContaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DevolveActividadesEdicaoUtilizadorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AlterarActividadeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetActividadeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DevolveColaboradorInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CriarActividadeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.estagio_projeto.My.MySettings.Default.estagio_projeto_webserver_ClientService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event HelloWorldCompleted As HelloWorldCompletedEventHandler
        
        '''<remarks/>
        Public Event DevolveIncidenteIDCompleted As DevolveIncidenteIDCompletedEventHandler
        
        '''<remarks/>
        Public Event GetIncidenteCompleted As GetIncidenteCompletedEventHandler
        
        '''<remarks/>
        Public Event DevolveTipoIncidentesCompleted As DevolveTipoIncidentesCompletedEventHandler
        
        '''<remarks/>
        Public Event DevolveIncidentesActivosCompleted As DevolveIncidentesActivosCompletedEventHandler
        
        '''<remarks/>
        Public Event DevolveMeusIncidentesActivosCompleted As DevolveMeusIncidentesActivosCompletedEventHandler
        
        '''<remarks/>
        Public Event DevolveActividadesCompleted As DevolveActividadesCompletedEventHandler
        
        '''<remarks/>
        Public Event DevolveActividadesEdicaoContaCompleted As DevolveActividadesEdicaoContaCompletedEventHandler
        
        '''<remarks/>
        Public Event DevolveActividadesEdicaoUtilizadorCompleted As DevolveActividadesEdicaoUtilizadorCompletedEventHandler
        
        '''<remarks/>
        Public Event AlterarActividadeCompleted As AlterarActividadeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetActividadeCompleted As GetActividadeCompletedEventHandler
        
        '''<remarks/>
        Public Event DevolveColaboradorInfoCompleted As DevolveColaboradorInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event CriarActividadeCompleted As CriarActividadeCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld() As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync()
            Me.HelloWorldAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync(ByVal userState As Object)
            If (Me.HelloWorldOperationCompleted Is Nothing) Then
                Me.HelloWorldOperationCompleted = AddressOf Me.OnHelloWorldOperationCompleted
            End If
            Me.InvokeAsync("HelloWorld", New Object(-1) {}, Me.HelloWorldOperationCompleted, userState)
        End Sub
        
        Private Sub OnHelloWorldOperationCompleted(ByVal arg As Object)
            If (Not (Me.HelloWorldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HelloWorldCompleted(Me, New HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevolveIncidenteID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DevolveIncidenteID(ByVal ticketnumber_arg As String) As String
            Dim results() As Object = Me.Invoke("DevolveIncidenteID", New Object() {ticketnumber_arg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DevolveIncidenteIDAsync(ByVal ticketnumber_arg As String)
            Me.DevolveIncidenteIDAsync(ticketnumber_arg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DevolveIncidenteIDAsync(ByVal ticketnumber_arg As String, ByVal userState As Object)
            If (Me.DevolveIncidenteIDOperationCompleted Is Nothing) Then
                Me.DevolveIncidenteIDOperationCompleted = AddressOf Me.OnDevolveIncidenteIDOperationCompleted
            End If
            Me.InvokeAsync("DevolveIncidenteID", New Object() {ticketnumber_arg}, Me.DevolveIncidenteIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnDevolveIncidenteIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.DevolveIncidenteIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DevolveIncidenteIDCompleted(Me, New DevolveIncidenteIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetIncidente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetIncidente(ByVal incidenteID_arg As String, ByVal lang As String) As clsIncidente
            Dim results() As Object = Me.Invoke("GetIncidente", New Object() {incidenteID_arg, lang})
            Return CType(results(0),clsIncidente)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetIncidenteAsync(ByVal incidenteID_arg As String, ByVal lang As String)
            Me.GetIncidenteAsync(incidenteID_arg, lang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetIncidenteAsync(ByVal incidenteID_arg As String, ByVal lang As String, ByVal userState As Object)
            If (Me.GetIncidenteOperationCompleted Is Nothing) Then
                Me.GetIncidenteOperationCompleted = AddressOf Me.OnGetIncidenteOperationCompleted
            End If
            Me.InvokeAsync("GetIncidente", New Object() {incidenteID_arg, lang}, Me.GetIncidenteOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetIncidenteOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetIncidenteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetIncidenteCompleted(Me, New GetIncidenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevolveTipoIncidentes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DevolveTipoIncidentes(ByVal lang As String) As clsTipoIncidente()
            Dim results() As Object = Me.Invoke("DevolveTipoIncidentes", New Object() {lang})
            Return CType(results(0),clsTipoIncidente())
        End Function
        
        '''<remarks/>
        Public Overloads Sub DevolveTipoIncidentesAsync(ByVal lang As String)
            Me.DevolveTipoIncidentesAsync(lang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DevolveTipoIncidentesAsync(ByVal lang As String, ByVal userState As Object)
            If (Me.DevolveTipoIncidentesOperationCompleted Is Nothing) Then
                Me.DevolveTipoIncidentesOperationCompleted = AddressOf Me.OnDevolveTipoIncidentesOperationCompleted
            End If
            Me.InvokeAsync("DevolveTipoIncidentes", New Object() {lang}, Me.DevolveTipoIncidentesOperationCompleted, userState)
        End Sub
        
        Private Sub OnDevolveTipoIncidentesOperationCompleted(ByVal arg As Object)
            If (Not (Me.DevolveTipoIncidentesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DevolveTipoIncidentesCompleted(Me, New DevolveTipoIncidentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevolveIncidentesActivos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DevolveIncidentesActivos(ByVal empresaID_arg As String, ByVal tipoIncidente_arg As eTipoIncidente, ByVal lang As String) As clsIncidente()
            Dim results() As Object = Me.Invoke("DevolveIncidentesActivos", New Object() {empresaID_arg, tipoIncidente_arg, lang})
            Return CType(results(0),clsIncidente())
        End Function
        
        '''<remarks/>
        Public Overloads Sub DevolveIncidentesActivosAsync(ByVal empresaID_arg As String, ByVal tipoIncidente_arg As eTipoIncidente, ByVal lang As String)
            Me.DevolveIncidentesActivosAsync(empresaID_arg, tipoIncidente_arg, lang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DevolveIncidentesActivosAsync(ByVal empresaID_arg As String, ByVal tipoIncidente_arg As eTipoIncidente, ByVal lang As String, ByVal userState As Object)
            If (Me.DevolveIncidentesActivosOperationCompleted Is Nothing) Then
                Me.DevolveIncidentesActivosOperationCompleted = AddressOf Me.OnDevolveIncidentesActivosOperationCompleted
            End If
            Me.InvokeAsync("DevolveIncidentesActivos", New Object() {empresaID_arg, tipoIncidente_arg, lang}, Me.DevolveIncidentesActivosOperationCompleted, userState)
        End Sub
        
        Private Sub OnDevolveIncidentesActivosOperationCompleted(ByVal arg As Object)
            If (Not (Me.DevolveIncidentesActivosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DevolveIncidentesActivosCompleted(Me, New DevolveIncidentesActivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevolveMeusIncidentesActivos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DevolveMeusIncidentesActivos(ByVal utilizadorID_arg As String, ByVal razaoEstado_arg As RazaoEstado, ByVal tipoIncidente_arg As eTipoIncidente, ByVal lang As String) As clsIncidente()
            Dim results() As Object = Me.Invoke("DevolveMeusIncidentesActivos", New Object() {utilizadorID_arg, razaoEstado_arg, tipoIncidente_arg, lang})
            Return CType(results(0),clsIncidente())
        End Function
        
        '''<remarks/>
        Public Overloads Sub DevolveMeusIncidentesActivosAsync(ByVal utilizadorID_arg As String, ByVal razaoEstado_arg As RazaoEstado, ByVal tipoIncidente_arg As eTipoIncidente, ByVal lang As String)
            Me.DevolveMeusIncidentesActivosAsync(utilizadorID_arg, razaoEstado_arg, tipoIncidente_arg, lang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DevolveMeusIncidentesActivosAsync(ByVal utilizadorID_arg As String, ByVal razaoEstado_arg As RazaoEstado, ByVal tipoIncidente_arg As eTipoIncidente, ByVal lang As String, ByVal userState As Object)
            If (Me.DevolveMeusIncidentesActivosOperationCompleted Is Nothing) Then
                Me.DevolveMeusIncidentesActivosOperationCompleted = AddressOf Me.OnDevolveMeusIncidentesActivosOperationCompleted
            End If
            Me.InvokeAsync("DevolveMeusIncidentesActivos", New Object() {utilizadorID_arg, razaoEstado_arg, tipoIncidente_arg, lang}, Me.DevolveMeusIncidentesActivosOperationCompleted, userState)
        End Sub
        
        Private Sub OnDevolveMeusIncidentesActivosOperationCompleted(ByVal arg As Object)
            If (Not (Me.DevolveMeusIncidentesActivosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DevolveMeusIncidentesActivosCompleted(Me, New DevolveMeusIncidentesActivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevolveActividades", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DevolveActividades(ByVal incidentID_arg As String, ByVal fechado_arg As Boolean, ByVal lang As String) As clsActividade()
            Dim results() As Object = Me.Invoke("DevolveActividades", New Object() {incidentID_arg, fechado_arg, lang})
            Return CType(results(0),clsActividade())
        End Function
        
        '''<remarks/>
        Public Overloads Sub DevolveActividadesAsync(ByVal incidentID_arg As String, ByVal fechado_arg As Boolean, ByVal lang As String)
            Me.DevolveActividadesAsync(incidentID_arg, fechado_arg, lang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DevolveActividadesAsync(ByVal incidentID_arg As String, ByVal fechado_arg As Boolean, ByVal lang As String, ByVal userState As Object)
            If (Me.DevolveActividadesOperationCompleted Is Nothing) Then
                Me.DevolveActividadesOperationCompleted = AddressOf Me.OnDevolveActividadesOperationCompleted
            End If
            Me.InvokeAsync("DevolveActividades", New Object() {incidentID_arg, fechado_arg, lang}, Me.DevolveActividadesOperationCompleted, userState)
        End Sub
        
        Private Sub OnDevolveActividadesOperationCompleted(ByVal arg As Object)
            If (Not (Me.DevolveActividadesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DevolveActividadesCompleted(Me, New DevolveActividadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevolveActividadesEdicaoConta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DevolveActividadesEdicaoConta(ByVal contaID_arg As String, ByVal lang As String) As clsActividade()
            Dim results() As Object = Me.Invoke("DevolveActividadesEdicaoConta", New Object() {contaID_arg, lang})
            Return CType(results(0),clsActividade())
        End Function
        
        '''<remarks/>
        Public Overloads Sub DevolveActividadesEdicaoContaAsync(ByVal contaID_arg As String, ByVal lang As String)
            Me.DevolveActividadesEdicaoContaAsync(contaID_arg, lang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DevolveActividadesEdicaoContaAsync(ByVal contaID_arg As String, ByVal lang As String, ByVal userState As Object)
            If (Me.DevolveActividadesEdicaoContaOperationCompleted Is Nothing) Then
                Me.DevolveActividadesEdicaoContaOperationCompleted = AddressOf Me.OnDevolveActividadesEdicaoContaOperationCompleted
            End If
            Me.InvokeAsync("DevolveActividadesEdicaoConta", New Object() {contaID_arg, lang}, Me.DevolveActividadesEdicaoContaOperationCompleted, userState)
        End Sub
        
        Private Sub OnDevolveActividadesEdicaoContaOperationCompleted(ByVal arg As Object)
            If (Not (Me.DevolveActividadesEdicaoContaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DevolveActividadesEdicaoContaCompleted(Me, New DevolveActividadesEdicaoContaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevolveActividadesEdicaoUtilizador", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DevolveActividadesEdicaoUtilizador(ByVal utilizadorID_arg As String, ByVal lang As String) As clsActividade()
            Dim results() As Object = Me.Invoke("DevolveActividadesEdicaoUtilizador", New Object() {utilizadorID_arg, lang})
            Return CType(results(0),clsActividade())
        End Function
        
        '''<remarks/>
        Public Overloads Sub DevolveActividadesEdicaoUtilizadorAsync(ByVal utilizadorID_arg As String, ByVal lang As String)
            Me.DevolveActividadesEdicaoUtilizadorAsync(utilizadorID_arg, lang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DevolveActividadesEdicaoUtilizadorAsync(ByVal utilizadorID_arg As String, ByVal lang As String, ByVal userState As Object)
            If (Me.DevolveActividadesEdicaoUtilizadorOperationCompleted Is Nothing) Then
                Me.DevolveActividadesEdicaoUtilizadorOperationCompleted = AddressOf Me.OnDevolveActividadesEdicaoUtilizadorOperationCompleted
            End If
            Me.InvokeAsync("DevolveActividadesEdicaoUtilizador", New Object() {utilizadorID_arg, lang}, Me.DevolveActividadesEdicaoUtilizadorOperationCompleted, userState)
        End Sub
        
        Private Sub OnDevolveActividadesEdicaoUtilizadorOperationCompleted(ByVal arg As Object)
            If (Not (Me.DevolveActividadesEdicaoUtilizadorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DevolveActividadesEdicaoUtilizadorCompleted(Me, New DevolveActividadesEdicaoUtilizadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlterarActividade", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AlterarActividade(ByVal act_arg As clsActividade) As String
            Dim results() As Object = Me.Invoke("AlterarActividade", New Object() {act_arg})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AlterarActividadeAsync(ByVal act_arg As clsActividade)
            Me.AlterarActividadeAsync(act_arg, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AlterarActividadeAsync(ByVal act_arg As clsActividade, ByVal userState As Object)
            If (Me.AlterarActividadeOperationCompleted Is Nothing) Then
                Me.AlterarActividadeOperationCompleted = AddressOf Me.OnAlterarActividadeOperationCompleted
            End If
            Me.InvokeAsync("AlterarActividade", New Object() {act_arg}, Me.AlterarActividadeOperationCompleted, userState)
        End Sub
        
        Private Sub OnAlterarActividadeOperationCompleted(ByVal arg As Object)
            If (Not (Me.AlterarActividadeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AlterarActividadeCompleted(Me, New AlterarActividadeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetActividade", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetActividade(ByVal actividadeID_arg As String, ByVal lang As String) As clsActividade
            Dim results() As Object = Me.Invoke("GetActividade", New Object() {actividadeID_arg, lang})
            Return CType(results(0),clsActividade)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetActividadeAsync(ByVal actividadeID_arg As String, ByVal lang As String)
            Me.GetActividadeAsync(actividadeID_arg, lang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetActividadeAsync(ByVal actividadeID_arg As String, ByVal lang As String, ByVal userState As Object)
            If (Me.GetActividadeOperationCompleted Is Nothing) Then
                Me.GetActividadeOperationCompleted = AddressOf Me.OnGetActividadeOperationCompleted
            End If
            Me.InvokeAsync("GetActividade", New Object() {actividadeID_arg, lang}, Me.GetActividadeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetActividadeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetActividadeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetActividadeCompleted(Me, New GetActividadeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevolveColaboradorInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DevolveColaboradorInfo(ByVal user_arg As String, ByVal lang As String) As clsColaborador
            Dim results() As Object = Me.Invoke("DevolveColaboradorInfo", New Object() {user_arg, lang})
            Return CType(results(0),clsColaborador)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DevolveColaboradorInfoAsync(ByVal user_arg As String, ByVal lang As String)
            Me.DevolveColaboradorInfoAsync(user_arg, lang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DevolveColaboradorInfoAsync(ByVal user_arg As String, ByVal lang As String, ByVal userState As Object)
            If (Me.DevolveColaboradorInfoOperationCompleted Is Nothing) Then
                Me.DevolveColaboradorInfoOperationCompleted = AddressOf Me.OnDevolveColaboradorInfoOperationCompleted
            End If
            Me.InvokeAsync("DevolveColaboradorInfo", New Object() {user_arg, lang}, Me.DevolveColaboradorInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnDevolveColaboradorInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.DevolveColaboradorInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DevolveColaboradorInfoCompleted(Me, New DevolveColaboradorInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CriarActividade", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CriarActividade(ByVal act_arg As clsActividade, ByVal lang As String) As clsErro
            Dim results() As Object = Me.Invoke("CriarActividade", New Object() {act_arg, lang})
            Return CType(results(0),clsErro)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CriarActividadeAsync(ByVal act_arg As clsActividade, ByVal lang As String)
            Me.CriarActividadeAsync(act_arg, lang, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CriarActividadeAsync(ByVal act_arg As clsActividade, ByVal lang As String, ByVal userState As Object)
            If (Me.CriarActividadeOperationCompleted Is Nothing) Then
                Me.CriarActividadeOperationCompleted = AddressOf Me.OnCriarActividadeOperationCompleted
            End If
            Me.InvokeAsync("CriarActividade", New Object() {act_arg, lang}, Me.CriarActividadeOperationCompleted, userState)
        End Sub
        
        Private Sub OnCriarActividadeOperationCompleted(ByVal arg As Object)
            If (Not (Me.CriarActividadeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CriarActividadeCompleted(Me, New CriarActividadeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsIncidente
        
        Private idField As String
        
        Private clienteIDField As String
        
        Private clienteNomeField As String
        
        Private contactoIDField As String
        
        Private contactoNomeField As String
        
        Private resumoField As String
        
        Private descricaoField As String
        
        Private dataAberturaField As Date
        
        Private dataInicioField As Date
        
        Private dataFechoField As Date
        
        Private dataSolucionamentoField As Date
        
        Private prioridadeField As String
        
        Private prioridadeIDField As Integer
        
        Private numeroField As String
        
        Private estadoField As String
        
        Private razaoEstadoField As String
        
        Private sLASDField As String
        
        Private sLASD_DecField As Double
        
        Private assuntoField As String
        
        Private clsAssuntoField As clsAssunto
        
        Private proprietarioNomeField As String
        
        Private proprietarioIDField As String
        
        Private moradaField As clsMorada
        
        Private aprovadoPorField As String
        
        Private dataAprovacaoField As Date
        
        Private impactoField As String
        
        Private urgenciaField As String
        
        Private duracaoTotalField As String
        
        Private descontoTotalField As String
        
        Private duracaoTotalLiquidoField As String
        
        Private duracaoTotalDecField As Double
        
        Private descontoTotalDecField As Double
        
        Private validadoField As Boolean
        
        Private observacoesField As String
        
        Private grauSatisfacaoField As eSatisfacao
        
        Private numeroRefeicoesField As Integer
        
        Private numeroEstadiasField As Integer
        
        Private numeroDeslocacoesACField As Integer
        
        Private numeroDeslocacoesField As Integer
        
        Private solucionadoPorNomeField As String
        
        Private solucionadoPorIDField As String
        
        Private periodoSolucionamentoUltrapassadoField As Boolean
        
        Private dataNaoSolucionamentoField As Date
        
        Private anexoField As clsAnexo
        
        Private tempoResolucaoField As String
        
        Private tipoIncidenteField As eTipoIncidente
        
        Private tipoAssistenciaField As Integer
        
        Private tipoPedidoField As Integer
        
        Private contratoIDField As String
        
        Private linhaContratoIDField As String
        
        Private motivoatrasoSlaSDField As String
        
        Private origemIDField As Integer
        
        Private tipoContratoField As eTipoContrato
        
        Private agendamentoField As Boolean
        
        Private empresaIDField As String
        
        Private criadoPorField As String
        
        '''<remarks/>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClienteID() As String
            Get
                Return Me.clienteIDField
            End Get
            Set
                Me.clienteIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClienteNome() As String
            Get
                Return Me.clienteNomeField
            End Get
            Set
                Me.clienteNomeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContactoID() As String
            Get
                Return Me.contactoIDField
            End Get
            Set
                Me.contactoIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContactoNome() As String
            Get
                Return Me.contactoNomeField
            End Get
            Set
                Me.contactoNomeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Resumo() As String
            Get
                Return Me.resumoField
            End Get
            Set
                Me.resumoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descricao() As String
            Get
                Return Me.descricaoField
            End Get
            Set
                Me.descricaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataAbertura() As Date
            Get
                Return Me.dataAberturaField
            End Get
            Set
                Me.dataAberturaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataInicio() As Date
            Get
                Return Me.dataInicioField
            End Get
            Set
                Me.dataInicioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataFecho() As Date
            Get
                Return Me.dataFechoField
            End Get
            Set
                Me.dataFechoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataSolucionamento() As Date
            Get
                Return Me.dataSolucionamentoField
            End Get
            Set
                Me.dataSolucionamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Prioridade() As String
            Get
                Return Me.prioridadeField
            End Get
            Set
                Me.prioridadeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrioridadeID() As Integer
            Get
                Return Me.prioridadeIDField
            End Get
            Set
                Me.prioridadeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RazaoEstado() As String
            Get
                Return Me.razaoEstadoField
            End Get
            Set
                Me.razaoEstadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SLASD() As String
            Get
                Return Me.sLASDField
            End Get
            Set
                Me.sLASDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SLASD_Dec() As Double
            Get
                Return Me.sLASD_DecField
            End Get
            Set
                Me.sLASD_DecField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Assunto() As String
            Get
                Return Me.assuntoField
            End Get
            Set
                Me.assuntoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClsAssunto() As clsAssunto
            Get
                Return Me.clsAssuntoField
            End Get
            Set
                Me.clsAssuntoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProprietarioNome() As String
            Get
                Return Me.proprietarioNomeField
            End Get
            Set
                Me.proprietarioNomeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProprietarioID() As String
            Get
                Return Me.proprietarioIDField
            End Get
            Set
                Me.proprietarioIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Morada() As clsMorada
            Get
                Return Me.moradaField
            End Get
            Set
                Me.moradaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AprovadoPor() As String
            Get
                Return Me.aprovadoPorField
            End Get
            Set
                Me.aprovadoPorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataAprovacao() As Date
            Get
                Return Me.dataAprovacaoField
            End Get
            Set
                Me.dataAprovacaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Impacto() As String
            Get
                Return Me.impactoField
            End Get
            Set
                Me.impactoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Urgencia() As String
            Get
                Return Me.urgenciaField
            End Get
            Set
                Me.urgenciaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DuracaoTotal() As String
            Get
                Return Me.duracaoTotalField
            End Get
            Set
                Me.duracaoTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescontoTotal() As String
            Get
                Return Me.descontoTotalField
            End Get
            Set
                Me.descontoTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DuracaoTotalLiquido() As String
            Get
                Return Me.duracaoTotalLiquidoField
            End Get
            Set
                Me.duracaoTotalLiquidoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DuracaoTotalDec() As Double
            Get
                Return Me.duracaoTotalDecField
            End Get
            Set
                Me.duracaoTotalDecField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescontoTotalDec() As Double
            Get
                Return Me.descontoTotalDecField
            End Get
            Set
                Me.descontoTotalDecField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Validado() As Boolean
            Get
                Return Me.validadoField
            End Get
            Set
                Me.validadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Observacoes() As String
            Get
                Return Me.observacoesField
            End Get
            Set
                Me.observacoesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GrauSatisfacao() As eSatisfacao
            Get
                Return Me.grauSatisfacaoField
            End Get
            Set
                Me.grauSatisfacaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroRefeicoes() As Integer
            Get
                Return Me.numeroRefeicoesField
            End Get
            Set
                Me.numeroRefeicoesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroEstadias() As Integer
            Get
                Return Me.numeroEstadiasField
            End Get
            Set
                Me.numeroEstadiasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroDeslocacoesAC() As Integer
            Get
                Return Me.numeroDeslocacoesACField
            End Get
            Set
                Me.numeroDeslocacoesACField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroDeslocacoes() As Integer
            Get
                Return Me.numeroDeslocacoesField
            End Get
            Set
                Me.numeroDeslocacoesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SolucionadoPorNome() As String
            Get
                Return Me.solucionadoPorNomeField
            End Get
            Set
                Me.solucionadoPorNomeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SolucionadoPorID() As String
            Get
                Return Me.solucionadoPorIDField
            End Get
            Set
                Me.solucionadoPorIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PeriodoSolucionamentoUltrapassado() As Boolean
            Get
                Return Me.periodoSolucionamentoUltrapassadoField
            End Get
            Set
                Me.periodoSolucionamentoUltrapassadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataNaoSolucionamento() As Date
            Get
                Return Me.dataNaoSolucionamentoField
            End Get
            Set
                Me.dataNaoSolucionamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Anexo() As clsAnexo
            Get
                Return Me.anexoField
            End Get
            Set
                Me.anexoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TempoResolucao() As String
            Get
                Return Me.tempoResolucaoField
            End Get
            Set
                Me.tempoResolucaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoIncidente() As eTipoIncidente
            Get
                Return Me.tipoIncidenteField
            End Get
            Set
                Me.tipoIncidenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoAssistencia() As Integer
            Get
                Return Me.tipoAssistenciaField
            End Get
            Set
                Me.tipoAssistenciaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoPedido() As Integer
            Get
                Return Me.tipoPedidoField
            End Get
            Set
                Me.tipoPedidoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContratoID() As String
            Get
                Return Me.contratoIDField
            End Get
            Set
                Me.contratoIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LinhaContratoID() As String
            Get
                Return Me.linhaContratoIDField
            End Get
            Set
                Me.linhaContratoIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MotivoatrasoSlaSD() As String
            Get
                Return Me.motivoatrasoSlaSDField
            End Get
            Set
                Me.motivoatrasoSlaSDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrigemID() As Integer
            Get
                Return Me.origemIDField
            End Get
            Set
                Me.origemIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoContrato() As eTipoContrato
            Get
                Return Me.tipoContratoField
            End Get
            Set
                Me.tipoContratoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Agendamento() As Boolean
            Get
                Return Me.agendamentoField
            End Get
            Set
                Me.agendamentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmpresaID() As String
            Get
                Return Me.empresaIDField
            End Get
            Set
                Me.empresaIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CriadoPor() As String
            Get
                Return Me.criadoPorField
            End Get
            Set
                Me.criadoPorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsAssunto
        
        Private nomeField As String
        
        Private idField As String
        
        Private codigoAssuntoGeralField As String
        
        Private iDAssuntoGeralField As String
        
        Private assuntoInternoField As Boolean
        
        '''<remarks/>
        Public Property Nome() As String
            Get
                Return Me.nomeField
            End Get
            Set
                Me.nomeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoAssuntoGeral() As String
            Get
                Return Me.codigoAssuntoGeralField
            End Get
            Set
                Me.codigoAssuntoGeralField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDAssuntoGeral() As String
            Get
                Return Me.iDAssuntoGeralField
            End Get
            Set
                Me.iDAssuntoGeralField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AssuntoInterno() As Boolean
            Get
                Return Me.assuntoInternoField
            End Get
            Set
                Me.assuntoInternoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsErro
        
        Private erroField As Boolean
        
        Private avisoField As Boolean
        
        Private erroDescricaoField As String
        
        Private avisoDescricaoField As String
        
        Private textoField As String
        
        Private texto2Field As String
        
        '''<remarks/>
        Public Property Erro() As Boolean
            Get
                Return Me.erroField
            End Get
            Set
                Me.erroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Aviso() As Boolean
            Get
                Return Me.avisoField
            End Get
            Set
                Me.avisoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErroDescricao() As String
            Get
                Return Me.erroDescricaoField
            End Get
            Set
                Me.erroDescricaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AvisoDescricao() As String
            Get
                Return Me.avisoDescricaoField
            End Get
            Set
                Me.avisoDescricaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Texto() As String
            Get
                Return Me.textoField
            End Get
            Set
                Me.textoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Texto2() As String
            Get
                Return Me.texto2Field
            End Get
            Set
                Me.texto2Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsEquipa
        
        Private idField As String
        
        Private nomeField As String
        
        '''<remarks/>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nome() As String
            Get
                Return Me.nomeField
            End Get
            Set
                Me.nomeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsColaborador
        
        Private idField As String
        
        Private nomeField As String
        
        Private equipaField As clsEquipa
        
        Private gestorEquipaField As Boolean
        
        Private administradorField As Boolean
        
        Private acessoPicagemField As Boolean
        
        '''<remarks/>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nome() As String
            Get
                Return Me.nomeField
            End Get
            Set
                Me.nomeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Equipa() As clsEquipa
            Get
                Return Me.equipaField
            End Get
            Set
                Me.equipaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GestorEquipa() As Boolean
            Get
                Return Me.gestorEquipaField
            End Get
            Set
                Me.gestorEquipaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Administrador() As Boolean
            Get
                Return Me.administradorField
            End Get
            Set
                Me.administradorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AcessoPicagem() As Boolean
            Get
                Return Me.acessoPicagemField
            End Get
            Set
                Me.acessoPicagemField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsActividade
        
        Private idField As String
        
        Private codigoIncidenteField As String
        
        Private assuntoField As String
        
        Private descricaoField As String
        
        Private dataInicioField As Date
        
        Private dataFimField As Date
        
        Private servicoField As String
        
        Private modoAssistenciaField As String
        
        Private recursosField As String
        
        Private duracaoPrevistaField As String
        
        Private duracaoRealField As String
        
        Private duracaoDeslocacaoField As String
        
        Private numeroGuiaAssistenciaField As String
        
        Private descontoClienteField As String
        
        Private descricaoDescontoClienteField As String
        
        Private periodoFechoUltrapassadoField As Boolean
        
        Private estadoField As String
        
        Private dataFechoField As Date
        
        Private validadoClienteField As Integer
        
        Private validadoPorIDField As String
        
        Private validadoEmField As Date
        
        Private validadoPorNomeField As String
        
        Private numDeslocacoesField As Integer
        
        Private numRefeicoesField As Integer
        
        Private vistoField As Boolean
        
        Private iDClienteField As String
        
        Private nomeClienteField As String
        
        Private descontoTecnicoField As String
        
        Private descricaoDescontoTecnicoField As String
        
        Private descontoGestorField As String
        
        Private descricaoDescontoGestorField As String
        
        Private descontoComercialField As String
        
        Private descricaoDescontoComercialField As String
        
        Private vistoPorNomeField As String
        
        Private idIncidenteField As String
        
        Private descricaoIncidenteField As String
        
        Private projectoNomeField As String
        
        Private projectoIDField As String
        
        Private linhaContratoIDField As String
        
        Private linhaContratoDescricaoField As String
        
        Private contratoContinuidadeGexorField As Boolean
        
        Private suporteGlobalField As Boolean
        
        Private nCreditosField As Double
        
        Private actividadeDespesaField As Boolean
        
        Private kmsFacturadosField As Double
        
        '''<remarks/>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoIncidente() As String
            Get
                Return Me.codigoIncidenteField
            End Get
            Set
                Me.codigoIncidenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Assunto() As String
            Get
                Return Me.assuntoField
            End Get
            Set
                Me.assuntoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descricao() As String
            Get
                Return Me.descricaoField
            End Get
            Set
                Me.descricaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataInicio() As Date
            Get
                Return Me.dataInicioField
            End Get
            Set
                Me.dataInicioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataFim() As Date
            Get
                Return Me.dataFimField
            End Get
            Set
                Me.dataFimField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Servico() As String
            Get
                Return Me.servicoField
            End Get
            Set
                Me.servicoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ModoAssistencia() As String
            Get
                Return Me.modoAssistenciaField
            End Get
            Set
                Me.modoAssistenciaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Recursos() As String
            Get
                Return Me.recursosField
            End Get
            Set
                Me.recursosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DuracaoPrevista() As String
            Get
                Return Me.duracaoPrevistaField
            End Get
            Set
                Me.duracaoPrevistaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DuracaoReal() As String
            Get
                Return Me.duracaoRealField
            End Get
            Set
                Me.duracaoRealField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DuracaoDeslocacao() As String
            Get
                Return Me.duracaoDeslocacaoField
            End Get
            Set
                Me.duracaoDeslocacaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumeroGuiaAssistencia() As String
            Get
                Return Me.numeroGuiaAssistenciaField
            End Get
            Set
                Me.numeroGuiaAssistenciaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescontoCliente() As String
            Get
                Return Me.descontoClienteField
            End Get
            Set
                Me.descontoClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescricaoDescontoCliente() As String
            Get
                Return Me.descricaoDescontoClienteField
            End Get
            Set
                Me.descricaoDescontoClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PeriodoFechoUltrapassado() As Boolean
            Get
                Return Me.periodoFechoUltrapassadoField
            End Get
            Set
                Me.periodoFechoUltrapassadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataFecho() As Date
            Get
                Return Me.dataFechoField
            End Get
            Set
                Me.dataFechoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValidadoCliente() As Integer
            Get
                Return Me.validadoClienteField
            End Get
            Set
                Me.validadoClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValidadoPorID() As String
            Get
                Return Me.validadoPorIDField
            End Get
            Set
                Me.validadoPorIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValidadoEm() As Date
            Get
                Return Me.validadoEmField
            End Get
            Set
                Me.validadoEmField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValidadoPorNome() As String
            Get
                Return Me.validadoPorNomeField
            End Get
            Set
                Me.validadoPorNomeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumDeslocacoes() As Integer
            Get
                Return Me.numDeslocacoesField
            End Get
            Set
                Me.numDeslocacoesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumRefeicoes() As Integer
            Get
                Return Me.numRefeicoesField
            End Get
            Set
                Me.numRefeicoesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Visto() As Boolean
            Get
                Return Me.vistoField
            End Get
            Set
                Me.vistoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDCliente() As String
            Get
                Return Me.iDClienteField
            End Get
            Set
                Me.iDClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NomeCliente() As String
            Get
                Return Me.nomeClienteField
            End Get
            Set
                Me.nomeClienteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescontoTecnico() As String
            Get
                Return Me.descontoTecnicoField
            End Get
            Set
                Me.descontoTecnicoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescricaoDescontoTecnico() As String
            Get
                Return Me.descricaoDescontoTecnicoField
            End Get
            Set
                Me.descricaoDescontoTecnicoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescontoGestor() As String
            Get
                Return Me.descontoGestorField
            End Get
            Set
                Me.descontoGestorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescricaoDescontoGestor() As String
            Get
                Return Me.descricaoDescontoGestorField
            End Get
            Set
                Me.descricaoDescontoGestorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescontoComercial() As String
            Get
                Return Me.descontoComercialField
            End Get
            Set
                Me.descontoComercialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescricaoDescontoComercial() As String
            Get
                Return Me.descricaoDescontoComercialField
            End Get
            Set
                Me.descricaoDescontoComercialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VistoPorNome() As String
            Get
                Return Me.vistoPorNomeField
            End Get
            Set
                Me.vistoPorNomeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdIncidente() As String
            Get
                Return Me.idIncidenteField
            End Get
            Set
                Me.idIncidenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescricaoIncidente() As String
            Get
                Return Me.descricaoIncidenteField
            End Get
            Set
                Me.descricaoIncidenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProjectoNome() As String
            Get
                Return Me.projectoNomeField
            End Get
            Set
                Me.projectoNomeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProjectoID() As String
            Get
                Return Me.projectoIDField
            End Get
            Set
                Me.projectoIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LinhaContratoID() As String
            Get
                Return Me.linhaContratoIDField
            End Get
            Set
                Me.linhaContratoIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LinhaContratoDescricao() As String
            Get
                Return Me.linhaContratoDescricaoField
            End Get
            Set
                Me.linhaContratoDescricaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ContratoContinuidadeGexor() As Boolean
            Get
                Return Me.contratoContinuidadeGexorField
            End Get
            Set
                Me.contratoContinuidadeGexorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SuporteGlobal() As Boolean
            Get
                Return Me.suporteGlobalField
            End Get
            Set
                Me.suporteGlobalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NCreditos() As Double
            Get
                Return Me.nCreditosField
            End Get
            Set
                Me.nCreditosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ActividadeDespesa() As Boolean
            Get
                Return Me.actividadeDespesaField
            End Get
            Set
                Me.actividadeDespesaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property KmsFacturados() As Double
            Get
                Return Me.kmsFacturadosField
            End Get
            Set
                Me.kmsFacturadosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsTipoIncidente
        
        Private idField As String
        
        Private descricaoField As String
        
        '''<remarks/>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Descricao() As String
            Get
                Return Me.descricaoField
            End Get
            Set
                Me.descricaoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsAnexo
        
        Private nomeFicheiroField As String
        
        Private extensaoField As String
        
        Private tipoAnexoField As String
        
        Private dadosField() As Byte
        
        '''<remarks/>
        Public Property NomeFicheiro() As String
            Get
                Return Me.nomeFicheiroField
            End Get
            Set
                Me.nomeFicheiroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Extensao() As String
            Get
                Return Me.extensaoField
            End Get
            Set
                Me.extensaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoAnexo() As String
            Get
                Return Me.tipoAnexoField
            End Get
            Set
                Me.tipoAnexoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Dados() As Byte()
            Get
                Return Me.dadosField
            End Get
            Set
                Me.dadosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsMorada
        
        Private idField As String
        
        Private nomeField As String
        
        Private rua1Field As String
        
        Private rua2Field As String
        
        Private localidadeField As String
        
        Private codigoPostalField As String
        
        '''<remarks/>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nome() As String
            Get
                Return Me.nomeField
            End Get
            Set
                Me.nomeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Rua1() As String
            Get
                Return Me.rua1Field
            End Get
            Set
                Me.rua1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Rua2() As String
            Get
                Return Me.rua2Field
            End Get
            Set
                Me.rua2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Localidade() As String
            Get
                Return Me.localidadeField
            End Get
            Set
                Me.localidadeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoPostal() As String
            Get
                Return Me.codigoPostalField
            End Get
            Set
                Me.codigoPostalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum eSatisfacao
        
        '''<remarks/>
        MuitoSatisfeito
        
        '''<remarks/>
        Satisfeito
        
        '''<remarks/>
        Neutro
        
        '''<remarks/>
        Insatisfeito
        
        '''<remarks/>
        MuitoInsatisfeito
        
        '''<remarks/>
        Nenhum
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum eTipoIncidente
        
        '''<remarks/>
        TodosIncidentes
        
        '''<remarks/>
        IncidenteCliente
        
        '''<remarks/>
        Reclamacao
        
        '''<remarks/>
        ContratoMensal
        
        '''<remarks/>
        IncidenteEmEspera
        
        '''<remarks/>
        IncidenteIncentea
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum eTipoContrato
        
        '''<remarks/>
        SemContrato
        
        '''<remarks/>
        ContratoMensal
        
        '''<remarks/>
        PacoteCredito
        
        '''<remarks/>
        ProActivo
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum RazaoEstado
        
        '''<remarks/>
        Todos
        
        '''<remarks/>
        EmCurso
        
        '''<remarks/>
        IncidenteSuspenso
        
        '''<remarks/>
        ProblemaResolvido
        
        '''<remarks/>
        Cancelado
        
        '''<remarks/>
        Registado
        
        '''<remarks/>
        Fechado
        
        '''<remarks/>
        RegistadoOnLine
        
        '''<remarks/>
        AprovadoOnLine
        
        '''<remarks/>
        EmEspera
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub HelloWorldCompletedEventHandler(ByVal sender As Object, ByVal e As HelloWorldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HelloWorldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub DevolveIncidenteIDCompletedEventHandler(ByVal sender As Object, ByVal e As DevolveIncidenteIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DevolveIncidenteIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub GetIncidenteCompletedEventHandler(ByVal sender As Object, ByVal e As GetIncidenteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetIncidenteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsIncidente
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsIncidente)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub DevolveTipoIncidentesCompletedEventHandler(ByVal sender As Object, ByVal e As DevolveTipoIncidentesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DevolveTipoIncidentesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsTipoIncidente()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsTipoIncidente())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub DevolveIncidentesActivosCompletedEventHandler(ByVal sender As Object, ByVal e As DevolveIncidentesActivosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DevolveIncidentesActivosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsIncidente()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsIncidente())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub DevolveMeusIncidentesActivosCompletedEventHandler(ByVal sender As Object, ByVal e As DevolveMeusIncidentesActivosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DevolveMeusIncidentesActivosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsIncidente()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsIncidente())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub DevolveActividadesCompletedEventHandler(ByVal sender As Object, ByVal e As DevolveActividadesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DevolveActividadesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsActividade()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsActividade())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub DevolveActividadesEdicaoContaCompletedEventHandler(ByVal sender As Object, ByVal e As DevolveActividadesEdicaoContaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DevolveActividadesEdicaoContaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsActividade()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsActividade())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub DevolveActividadesEdicaoUtilizadorCompletedEventHandler(ByVal sender As Object, ByVal e As DevolveActividadesEdicaoUtilizadorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DevolveActividadesEdicaoUtilizadorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsActividade()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsActividade())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub AlterarActividadeCompletedEventHandler(ByVal sender As Object, ByVal e As AlterarActividadeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AlterarActividadeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub GetActividadeCompletedEventHandler(ByVal sender As Object, ByVal e As GetActividadeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetActividadeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsActividade
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsActividade)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub DevolveColaboradorInfoCompletedEventHandler(ByVal sender As Object, ByVal e As DevolveColaboradorInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DevolveColaboradorInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsColaborador
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsColaborador)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub CriarActividadeCompletedEventHandler(ByVal sender As Object, ByVal e As CriarActividadeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CriarActividadeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As clsErro
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),clsErro)
            End Get
        End Property
    End Class
End Namespace
